# Generated by Django 2.1.7 on 2019-02-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(verbose_name='待做事项')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
                ('done_time', models.DateTimeField(auto_now=True, verbose_name='完成时间')),
                ('priority', models.IntegerField(choices=[(1, '重要'), (2, '一般'), (3, '日常')], default=3, verbose_name='优先级')),
                ('is_done', models.BooleanField(default=False, verbose_name='完成状态')),
            ],
            options={
                'verbose_name': '待完成事项',
                'verbose_name_plural': '待完成事项',
                'ordering': ['priority', 'add_time'],
            },
        ),
    ]
