# Generated by Django 2.1.7 on 2019-02-12 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=200, verbose_name='提醒内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('priority', models.IntegerField(choices=[(1, '紧急'), (2, '重要'), (3, '一般')], default=3, verbose_name='优先级')),
                ('is_done', models.BooleanField(default=False, verbose_name='完成状态')),
            ],
            options={
                'verbose_name': '事件提醒',
                'verbose_name_plural': '事件提醒',
                'ordering': ['priority', 'add_time'],
            },
        ),
    ]
