# Generated by Django 2.1.7 on 2019-02-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolists', '0002_todo_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='add_time',
            field=models.DateTimeField(auto_now=True, verbose_name='添加时间'),
        ),
    ]
