# Generated by Django 2.1.7 on 2019-02-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolists', '0002_todo_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='member_name',
            field=models.CharField(default='', max_length=50, verbose_name='成员姓名'),
        ),
    ]
