# Generated by Django 2.1.7 on 2019-02-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolists', '0003_todo_member_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='work_type',
            field=models.CharField(blank=True, choices=[('1', '安全管理'), ('2', '生产管理'), ('3', '质量管理'), ('4', '综合管理'), ('5', '物资管理'), ('5', '物资管理'), ('6', '宣传工作'), ('0', '日常工作')], default='0', max_length=50, null=True, verbose_name='工作类型'),
        ),
    ]
