# Generated by Django 2.1.7 on 2019-02-25 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolists', '0007_auto_20190225_2257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['priority', 'add_time'], 'verbose_name': '待完成事项', 'verbose_name_plural': '待完成事项'},
        ),
    ]
