# Generated by Django 2.1.7 on 2019-03-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolists', '0008_auto_20190225_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='plan_done_time',
            field=models.DateTimeField(auto_now=True, verbose_name='计划完成时间'),
        ),
    ]
