# Generated by Django 2.1.7 on 2019-03-02 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolists', '0010_auto_20190302_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
