# Generated by Django 2.1.7 on 2019-03-03 09:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolists', '0012_auto_20190302_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsualTodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(default='', max_length=50, verbose_name='成员姓名')),
                ('work_type', models.CharField(choices=[('1', '安全管理'), ('2', '生产管理'), ('3', '质量管理'), ('4', '综合管理'), ('5', '物资管理'), ('6', '宣传工作'), ('0', '日常工作')], default='0', max_length=50, verbose_name='工作类型')),
                ('contents', models.TextField(verbose_name='待做事项')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('done_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='完成时间')),
                ('plan_done_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='计划完成时间')),
                ('priority', models.IntegerField(choices=[(1, '重要'), (2, '一般'), (3, '日常')], default=3, verbose_name='优先级')),
                ('is_done', models.BooleanField(default=False, verbose_name='完成状态')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
            options={
                'verbose_name': '待完成事项',
                'verbose_name_plural': '待完成事项',
                'ordering': ['priority', 'add_time'],
            },
        ),
    ]
