# Generated by Django 2.1.7 on 2019-03-08 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolists', '0014_auto_20190307_0243'),
        ('todolists', '0014_auto_20190305_1436'),
    ]

    operations = [
    ]
