# Generated by Django 2.1.7 on 2019-03-18 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolists', '0016_merge_20190315_0920'),
        ('todolists', '0016_merge_20190311_1737'),
    ]

    operations = [
    ]
