# Generated by Django 2.1.7 on 2019-03-18 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolists', '0017_merge_20190315_1739'),
        ('todolists', '0017_merge_20190318_0953'),
    ]

    operations = [
    ]
