# Generated by Django 2.1.7 on 2019-03-28 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolists', '0018_merge_20190318_1707'),
        ('todolists', '0018_merge_20190318_1003'),
    ]

    operations = [
    ]
