# Generated by Django 2.1.7 on 2019-02-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=6),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='/media/image/default.png', upload_to='image/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='job',
            field=models.CharField(blank=True, choices=[('1', '工班长'), ('2', '安全员'), ('3', '物资员'), ('4', '综合管理员'), ('5', '宣传员'), ('0', '无')], default='0', max_length=50, null=True, verbose_name='职务'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nick_name',
            field=models.CharField(default='', max_length=50, verbose_name='姓名'),
        ),
    ]
