# Generated by Django 2.1.7 on 2019-02-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='management_work',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job',
            field=models.CharField(blank=True, choices=[('1', '工班长'), ('2', '安全员'), ('3', '物资员'), ('4', '综合管理员'), ('5', '宣传员')], default='', max_length=50, null=True, verbose_name='职务'),
        ),
    ]
