# Generated by Django 2.1.7 on 2019-03-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190311_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='image/%Y/%m'),
        ),
    ]
