# Generated by Django 2.1.7 on 2019-03-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190313_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='job',
            field=models.CharField(blank=True, choices=[('1', '工班长'), ('2', '安全员'), ('3', '物资管理员'), ('4', '综合管理员'), ('5', '宣传员'), ('6', '质量管理员'), ('0', '无')], default='0', max_length=50, null=True, verbose_name='职务'),
        ),
    ]
