# Generated by Django 2.1.7 on 2019-03-15 16:56

import DjangoUeditor.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_title', models.CharField(default='', max_length=100, verbose_name='检修流程标题')),
                ('process_cont', DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='检修流程内容')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '检修流程',
                'verbose_name_plural': '检修流程',
            },
        ),
        migrations.CreateModel(
            name='PlanArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(default='', max_length=100, verbose_name='计划标题')),
                ('article_cont', DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='计划内容')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
                ('article_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
            ],
            options={
                'verbose_name': '计划内容',
                'verbose_name_plural': '计划内容',
            },
        ),
        migrations.CreateModel(
            name='PlanTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_title', models.CharField(default='', max_length=100, verbose_name='计划总标题')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '计划总标题',
                'verbose_name_plural': '计划总标题',
            },
        ),
        migrations.CreateModel(
            name='PlanYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_year', models.IntegerField(default=2019, verbose_name='时间')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '计划时间',
                'verbose_name_plural': '计划时间',
            },
        ),
        migrations.AddField(
            model_name='planarticle',
            name='article_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.PlanYear', verbose_name='时间'),
        ),
    ]
