# Generated by Django 2.1.7 on 2019-02-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_title', models.TextField(verbose_name='计划标题')),
            ],
            options={
                'verbose_name': '计划标题',
                'verbose_name_plural': '计划标题',
            },
        ),
    ]
