# Generated by Django 2.1.7 on 2019-02-28 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(default='', max_length=100, verbose_name='计划标题')),
                ('article_cont', models.TextField(verbose_name='计划内容')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
                ('article_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
            ],
            options={
                'verbose_name': '计划内容',
                'verbose_name_plural': '计划内容',
            },
        ),
        migrations.AlterModelOptions(
            name='plantitle',
            options={'verbose_name': '计划总标题', 'verbose_name_plural': '计划总标题'},
        ),
        migrations.AddField(
            model_name='plantitle',
            name='add_time',
            field=models.DateTimeField(auto_now=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='plantitle',
            name='plan_title',
            field=models.CharField(default='', max_length=100, verbose_name='计划总标题'),
        ),
    ]
