# Generated by Django 2.1.7 on 2019-02-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20190228_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_title', models.CharField(default='', max_length=100, verbose_name='检修流程标题')),
                ('process_cont', models.TextField(default='', verbose_name='检修流程内容')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '检修流程',
                'verbose_name_plural': '检修流程',
            },
        ),
        migrations.AddField(
            model_name='planarticle',
            name='article_year',
            field=models.IntegerField(default=2019, max_length=50, verbose_name='时间'),
        ),
    ]
