# Generated by Django 2.1.7 on 2019-02-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_auto_20190228_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planarticle',
            name='article_year',
            field=models.IntegerField(default=2019, verbose_name='时间'),
        ),
    ]
