# Generated by Django 2.1.7 on 2019-02-28 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_auto_20190228_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_year', models.IntegerField(default=2019, verbose_name='时间')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '计划时间',
                'verbose_name_plural': '计划时间',
            },
        ),
        migrations.AlterField(
            model_name='planarticle',
            name='article_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.PlanYear', verbose_name='时间'),
        ),
    ]
