# Generated by Django 2.1.7 on 2019-03-13 20:21

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_auto_20190228_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintain',
            name='process_cont',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='检修流程内容'),
        ),
        migrations.AlterField(
            model_name='planarticle',
            name='article_cont',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='计划内容'),
        ),
    ]
