# Generated by Django 2.1.7 on 2019-03-03 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='', max_length=10, verbose_name='系统名称')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '系统名称',
                'verbose_name_plural': '系统名称',
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.TextField(default='', verbose_name='题目')),
                ('answer', models.TextField(default='', verbose_name='答案')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.CourseType', verbose_name='系统名')),
            ],
            options={
                'verbose_name': '系统名称',
                'verbose_name_plural': '系统名称',
            },
        ),
    ]
