# Generated by Django 2.1.7 on 2019-03-03 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberQuestionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_answer', models.TextField(default='', verbose_name='答案')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.CourseType', verbose_name='系统名')),
            ],
            options={
                'verbose_name': '成员答题记录',
                'verbose_name_plural': '成员答题记录',
            },
        ),
        migrations.AlterModelOptions(
            name='questionbank',
            options={'verbose_name': '题库', 'verbose_name_plural': '题库'},
        ),
        migrations.AddField(
            model_name='memberquestionrecord',
            name='record_question_title',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='question.QuestionBank', verbose_name='题目'),
        ),
        migrations.AddField(
            model_name='memberquestionrecord',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='答题人'),
        ),
    ]
