# Generated by Django 2.1.7 on 2019-03-15 16:56

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sch_title', models.CharField(default='', max_length=100, verbose_name='排班标题')),
                ('contents', DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='排班内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('scheduling_year', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plans.PlanYear', verbose_name='排班年份')),
            ],
            options={
                'verbose_name': '排班计划',
                'verbose_name_plural': '排班计划',
            },
        ),
    ]
