# Generated by Django 2.1.7 on 2019-03-08 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sch_title', models.CharField(default='', max_length=100, verbose_name='排班标题')),
                ('image', models.ImageField(default='', upload_to='scheduling/%Y/%m', verbose_name='排班表')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '排班计划',
                'verbose_name_plural': '排班计划',
            },
        ),
    ]
