# Generated by Django 2.1.7 on 2019-03-08 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_auto_20190228_1642'),
        ('comprehensive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='scheduling_year',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='plans.PlanYear', verbose_name='排班年份'),
        ),
    ]
