# Generated by Django 2.1.7 on 2019-03-11 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atsintroduce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='简介标题')),
                ('contents', models.TextField(verbose_name='简介内容')),
                ('image', models.ImageField(default='', upload_to='atsintroduce/%Y/%m', verbose_name='班组照片')),
                ('logo', models.ImageField(default='', upload_to='logo/%Y/%m', verbose_name='班组LOGO')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '班组简介',
                'verbose_name_plural': '班组简介',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='信息标题')),
                ('contents', models.TextField(verbose_name='信息内容')),
                ('image', models.ImageField(default='', upload_to='information/%Y/%m', verbose_name='内容附图')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '信息中心',
                'verbose_name_plural': '信息中心',
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='链接标题')),
                ('url', models.URLField(default='', verbose_name='链接地址')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '网站链接',
                'verbose_name_plural': '网站链接',
            },
        ),
    ]
