# Generated by Django 2.1.7 on 2019-03-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atsintroduce',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='atsintroduce/%Y/%m', verbose_name='班组照片'),
        ),
        migrations.AlterField(
            model_name='atsintroduce',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='logo/%Y/%m', verbose_name='班组LOGO'),
        ),
        migrations.AlterField(
            model_name='information',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='information/%Y/%m', verbose_name='内容附图'),
        ),
    ]
