# Generated by Django 2.1.7 on 2019-03-13 11:03

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='contents',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='信息内容\t'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='公告标题'),
        ),
    ]
