# Generated by Django 2.1.7 on 2019-03-13 20:21

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20190313_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atsintroduce',
            name='image',
        ),
        migrations.RemoveField(
            model_name='atsintroduce',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='information',
            name='image',
        ),
        migrations.AlterField(
            model_name='atsintroduce',
            name='contents',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='简介内容'),
        ),
        migrations.AlterField(
            model_name='information',
            name='contents',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='信息内容'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='contents',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='公告内容'),
        ),
    ]
