# Generated by Django 2.1.7 on 2019-03-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='访问地址'),
        ),
    ]
