# Generated by Django 2.1.7 on 2019-04-19 11:23

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20190318_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='title',
        ),
        migrations.AddField(
            model_name='notice',
            name='sld',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='安全文件学习'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banner/%Y/%m', verbose_name='轮播图'),
        ),
    ]
